install.packages("RCurl", dependencies=TRUE)
library(RCurl)
install.packages("rgdal")
library(rgdal)
library(sp)
install.packages("digest")
library(digest)
install.packages("ggplot2")
library(ggplot2)
install.packages("rgeos")
library(rgeos)
install.packages("maptools")
library(maptools)
update.packages(checkBuilt = TRUE, ask = FALSE)
